# Training

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

# ML 
import torch
import numpy as np

# Modules
import sys
sys.path.append("../")

from inference import create_model_architecture
from io_utils import add_results
from core import prepare_data, create_learner_object

# Further 
from fastai.callback.all import SaveModelCallback

# import csv
from pathlib import Path 

import joblib

## Functions for the Separate Training

In [ ]:
def train_central(run, partition, models_path, model_name, epochs, lr = 0.001, csv_path = "./results.csv", s=2, h=1, c_in=87, seq_len=96):

    # Find GPU, create DLS 
    device = torch.device("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
    dls, _, means, stds = prepare_data(partition, s=s, h=h)

    # Check and Create Path
    target_path = Path(models_path).resolve()
    target_path.mkdir(parents=True, exist_ok=True)

    # Safe means and stds
    stats_file = target_path / 'preprocessing_stats.joblib'

    if not stats_file.exists():
        target_path.mkdir(parents=True, exist_ok=True)
        joblib.dump({'means': means, 'stds': stds}, stats_file)

    # Create model and learer 
    model, model_name = create_model_architecture(model_name,  c_in=c_in, c_out=h, seq_len=seq_len)
    learn = create_learner_object(dls, model, device)

    # Training
    learn.path = target_path
    learn.fit_one_cycle(epochs, lr, cbs=SaveModelCallback(fname=model_name))
    learn.load(model_name)

    # Determine best result
    best_idx = np.argmin([r[1] for r in learn.recorder.values])
    val = learn.recorder.values[best_idx]
    
    # Safe as an array 
    results = {
        "train_loss": float(val[0]),     
        "val_loss": float(val[1]), 
        "mse": float(val[2]),
        "mae": float(val[3]),
        "rmse": float(val[4])
    }

    # Set Mode and add results to the csv file
    mode="central"
    mapping = {0: 'a', 1: 'b', 2: 'c'}
    mapped_val = mapping[partition]

    add_results(csv_path, run, mode, model_name, epochs, mapped_val, results)
    
    return results

## Separate Training

In [ ]:
models = [
    ("LSTM", 30),
    ("gMLP", 15),
    ("InceptionTime", 15),
    ("TSTPlus", 20),
    ("GRUPlus", 20),
]


# for run in range(3, 7):
for run in [10]:

    for partition, letter in [(0, "a"), (1, "b"), (2, "c")]:

        dynamic_path = f"../models/central/run_{run}/{letter}"

        for model, epochs in models:
            train_central(
                run=run, 
                partition=partition, 
                models_path=dynamic_path,
                model_name=model, 
                epochs=epochs, 
                h=30
            )

Better model found at epoch 0 with valid_loss value: 1050.62646484375.
Better model found at epoch 1 with valid_loss value: 1037.957275390625.
Better model found at epoch 2 with valid_loss value: 861.884521484375.
Better model found at epoch 3 with valid_loss value: 652.2576904296875.
Better model found at epoch 4 with valid_loss value: 444.2220153808594.
Better model found at epoch 5 with valid_loss value: 341.39154052734375.
Better model found at epoch 6 with valid_loss value: 296.4527587890625.
Better model found at epoch 7 with valid_loss value: 283.565673828125.
Better model found at epoch 8 with valid_loss value: 278.4282531738281.
Better model found at epoch 9 with valid_loss value: 272.179931640625.
Better model found at epoch 14 with valid_loss value: 271.75567626953125.
Better model found at epoch 21 with valid_loss value: 265.7578430175781.
Better model found at epoch 24 with valid_loss value: 259.77972412109375.

Better model found at epoch 0 with valid_loss value: 443.6128234863281.
Better model found at epoch 1 with valid_loss value: 213.54971313476562.
Better model found at epoch 5 with valid_loss value: 198.64781188964844.
Better model found at epoch 6 with valid_loss value: 183.625244140625.
Better model found at epoch 7 with valid_loss value: 180.93116760253906.
Better model found at epoch 8 with valid_loss value: 171.6120147705078.
Better model found at epoch 9 with valid_loss value: 138.54519653320312.
Better model found at epoch 10 with valid_loss value: 108.8299331665039.
Better model found at epoch 11 with valid_loss value: 93.48787689208984.

Better model found at epoch 0 with valid_loss value: 757.6194458007812.
Better model found at epoch 1 with valid_loss value: 598.774658203125.
Better model found at epoch 2 with valid_loss value: 327.35565185546875.
Better model found at epoch 3 with valid_loss value: 326.37213134765625.
Better model found at epoch 4 with valid_loss value: 287.4084777832031.
Better model found at epoch 5 with valid_loss value: 258.2106628417969.

Better model found at epoch 0 with valid_loss value: 5000.12744140625.
Better model found at epoch 1 with valid_loss value: 3024.43212890625.
Better model found at epoch 2 with valid_loss value: 788.3775634765625.
Better model found at epoch 3 with valid_loss value: 380.3654479980469.
Better model found at epoch 4 with valid_loss value: 282.3838195800781.
Better model found at epoch 8 with valid_loss value: 225.6937255859375.

Better model found at epoch 0 with valid_loss value: 1052.9866943359375.
Better model found at epoch 1 with valid_loss value: 1017.3773803710938.
Better model found at epoch 2 with valid_loss value: 701.3396606445312.
Better model found at epoch 3 with valid_loss value: 429.28887939453125.
Better model found at epoch 4 with valid_loss value: 307.6465759277344.
Better model found at epoch 5 with valid_loss value: 268.56634521484375.
Better model found at epoch 6 with valid_loss value: 252.9017333984375.
Better model found at epoch 7 with valid_loss value: 241.11264038085938.
Better model found at epoch 8 with valid_loss value: 215.16038513183594.
Better model found at epoch 9 with valid_loss value: 194.9692840576172.
Better model found at epoch 10 with valid_loss value: 169.111572265625.
Better model found at epoch 11 with valid_loss value: 158.46405029296875.
Better model found at epoch 12 with valid_loss value: 149.5730438232422.
Better model found at epoch 13 with valid_loss value: 140.42652893066406.
Better model found at epoch 14 with valid_loss value: 135.4916229248047.
Better model found at epoch 15 with valid_loss value: 133.66578674316406.
Better model found at epoch 16 with valid_loss value: 133.11740112304688.
Better model found at epoch 17 with valid_loss value: 132.1140899658203.
Better model found at epoch 18 with valid_loss value: 131.74525451660156.
Better model found at epoch 19 with valid_loss value: 131.6609344482422.

Better model found at epoch 0 with valid_loss value: 928.5107421875.
Better model found at epoch 1 with valid_loss value: 884.8369750976562.
Better model found at epoch 2 with valid_loss value: 637.71484375.
Better model found at epoch 3 with valid_loss value: 411.7742919921875.
Better model found at epoch 4 with valid_loss value: 239.08213806152344.
Better model found at epoch 5 with valid_loss value: 146.01580810546875.
Better model found at epoch 6 with valid_loss value: 129.03427124023438.
Better model found at epoch 7 with valid_loss value: 98.40338134765625.
Better model found at epoch 8 with valid_loss value: 88.16036987304688.
Better model found at epoch 9 with valid_loss value: 79.08162689208984.
Better model found at epoch 10 with valid_loss value: 73.79708862304688.
Better model found at epoch 11 with valid_loss value: 72.93778228759766.
Better model found at epoch 16 with valid_loss value: 68.97187042236328.
Better model found at epoch 17 with valid_loss value: 68.65208435058594.
Better model found at epoch 18 with valid_loss value: 65.78527069091797.
Better model found at epoch 19 with valid_loss value: 61.89694595336914.
Better model found at epoch 20 with valid_loss value: 61.63725280761719.
Better model found at epoch 21 with valid_loss value: 60.56608200073242.
Better model found at epoch 22 with valid_loss value: 60.535377502441406.
Better model found at epoch 23 with valid_loss value: 60.2261848449707.

Better model found at epoch 0 with valid_loss value: 406.94415283203125.
Better model found at epoch 1 with valid_loss value: 132.24612426757812.
Better model found at epoch 2 with valid_loss value: 110.35029602050781.
Better model found at epoch 3 with valid_loss value: 100.93962860107422.
Better model found at epoch 4 with valid_loss value: 82.48200988769531.
Better model found at epoch 5 with valid_loss value: 72.218017578125.
Better model found at epoch 10 with valid_loss value: 65.33155059814453.
Better model found at epoch 11 with valid_loss value: 56.33560562133789.

Better model found at epoch 0 with valid_loss value: 818.017578125.
Better model found at epoch 1 with valid_loss value: 624.7819213867188.
Better model found at epoch 2 with valid_loss value: 197.795166015625.
Better model found at epoch 3 with valid_loss value: 103.09246063232422.
Better model found at epoch 10 with valid_loss value: 102.07416534423828.

Better model found at epoch 0 with valid_loss value: 159.39205932617188.
Better model found at epoch 1 with valid_loss value: 148.53553771972656.
Better model found at epoch 12 with valid_loss value: 130.06918334960938.
Better model found at epoch 14 with valid_loss value: 114.29928588867188.
Better model found at epoch 15 with valid_loss value: 111.08396911621094.

Better model found at epoch 0 with valid_loss value: 925.440185546875.
Better model found at epoch 1 with valid_loss value: 804.1318969726562.
Better model found at epoch 2 with valid_loss value: 475.0948181152344.
Better model found at epoch 3 with valid_loss value: 243.1633758544922.
Better model found at epoch 4 with valid_loss value: 147.83526611328125.
Better model found at epoch 5 with valid_loss value: 116.19540405273438.
Better model found at epoch 6 with valid_loss value: 102.574462890625.
Better model found at epoch 7 with valid_loss value: 88.87311553955078.
Better model found at epoch 8 with valid_loss value: 86.31687927246094.
Better model found at epoch 9 with valid_loss value: 83.90474700927734.
Better model found at epoch 10 with valid_loss value: 80.1819076538086.
Better model found at epoch 11 with valid_loss value: 76.13401794433594.
Better model found at epoch 12 with valid_loss value: 72.93325805664062.
Better model found at epoch 13 with valid_loss value: 70.59664154052734.
Better model found at epoch 14 with valid_loss value: 69.40419006347656.

Better model found at epoch 0 with valid_loss value: 944.0559692382812.
Better model found at epoch 1 with valid_loss value: 919.5043334960938.
Better model found at epoch 2 with valid_loss value: 670.41845703125.
Better model found at epoch 3 with valid_loss value: 438.2396240234375.
Better model found at epoch 4 with valid_loss value: 262.6146545410156.
Better model found at epoch 5 with valid_loss value: 163.46697998046875.
Better model found at epoch 6 with valid_loss value: 120.49600982666016.
Better model found at epoch 7 with valid_loss value: 104.3673324584961.
Better model found at epoch 8 with valid_loss value: 99.36573028564453.
Better model found at epoch 9 with valid_loss value: 92.95655822753906.
Better model found at epoch 10 with valid_loss value: 83.35798645019531.
Better model found at epoch 11 with valid_loss value: 77.38849639892578.
Better model found at epoch 12 with valid_loss value: 73.67959594726562.
Better model found at epoch 13 with valid_loss value: 73.17760467529297.

Better model found at epoch 0 with valid_loss value: 196.8050079345703.
Better model found at epoch 1 with valid_loss value: 128.65444946289062.
Better model found at epoch 2 with valid_loss value: 125.69384765625.
Better model found at epoch 3 with valid_loss value: 108.30522918701172.
Better model found at epoch 4 with valid_loss value: 93.90908813476562.
Better model found at epoch 6 with valid_loss value: 92.44660186767578.
Better model found at epoch 7 with valid_loss value: 90.26738739013672.
Better model found at epoch 9 with valid_loss value: 81.59520721435547.
Better model found at epoch 11 with valid_loss value: 65.65518188476562.
Better model found at epoch 12 with valid_loss value: 64.04796600341797.
Better model found at epoch 14 with valid_loss value: 63.80984115600586.

Better model found at epoch 0 with valid_loss value: 875.355712890625.
Better model found at epoch 1 with valid_loss value: 746.7905883789062.
Better model found at epoch 2 with valid_loss value: 607.5829467773438.
Better model found at epoch 3 with valid_loss value: 150.95663452148438.
Better model found at epoch 4 with valid_loss value: 115.06228637695312.
Better model found at epoch 6 with valid_loss value: 103.8795166015625.

Better model found at epoch 0 with valid_loss value: 927.7254028320312.
Better model found at epoch 1 with valid_loss value: 316.4643249511719.
Better model found at epoch 2 with valid_loss value: 235.28892517089844.
Better model found at epoch 3 with valid_loss value: 228.98497009277344.
Better model found at epoch 4 with valid_loss value: 144.89840698242188.
Better model found at epoch 12 with valid_loss value: 132.29627990722656.
Better model found at epoch 14 with valid_loss value: 102.88053894042969.

Better model found at epoch 0 with valid_loss value: 936.7334594726562.
Better model found at epoch 1 with valid_loss value: 848.55517578125.
Better model found at epoch 2 with valid_loss value: 515.0453491210938.
Better model found at epoch 3 with valid_loss value: 270.5760803222656.
Better model found at epoch 4 with valid_loss value: 160.04840087890625.
Better model found at epoch 5 with valid_loss value: 116.70076751708984.
Better model found at epoch 6 with valid_loss value: 104.6092529296875.
Better model found at epoch 7 with valid_loss value: 96.2525405883789.
Better model found at epoch 8 with valid_loss value: 94.91059112548828.
Better model found at epoch 9 with valid_loss value: 90.48917388916016.
Better model found at epoch 10 with valid_loss value: 84.58910369873047.
Better model found at epoch 11 with valid_loss value: 84.46929931640625.
Better model found at epoch 12 with valid_loss value: 80.52359008789062.
Better model found at epoch 13 with valid_loss value: 77.22803497314453.
Better model found at epoch 14 with valid_loss value: 74.94657135009766.
Better model found at epoch 15 with valid_loss value: 74.08187103271484.
Better model found at epoch 16 with valid_loss value: 74.00387573242188.

: